
[build]
  publish = "react-responsive-modal/.docz/dist"
  command = "yarn workspace react-responsive-modal docz:build"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.5"
  YARN_FLAGS = "--immutable"
