name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace react-responsive-modal lint

      - name: Test
        run: yarn workspace react-responsive-modal test --ci --coverage --maxWorkers=2

      - name: Report coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: yarn workspace react-responsive-modal build

      - name: Build docs
        run: yarn workspace website build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Dependencies already installed before
          install: false
          # Use monorepo
          project: ./react-responsive-modal
          start: yarn workspace website start -p 3000
