name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn workspace react-responsive-modal typecheck

      - name: Test
        run: yarn workspace react-responsive-modal test --ci --coverage --maxWorkers=2

      - name: Report coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: yarn workspace react-responsive-modal build

      - name: Build docs
        run: yarn workspace website build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Dependencies already installed before
          install: false
          # Use monorepo
          project: ./react-responsive-modal
          start: yarn workspace website start -p 3000

      - name: Size limit
        run: yarn workspace react-responsive-modal size
