name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: vite-plus setup
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Build
        run: vp run -r build

      - name: Check formatting, linting and type checks
        run: vp check

      - name: Test
        run: vp run -r test --coverage --run
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          install: false
          working-directory: ./react-responsive-modal
          start: vp run -F website start

      - name: Size limit
        run: vp run -F react-responsive-modal size
