name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
      pull-requests: write
      issues: write
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v6
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Use Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Build react-responsive-modal
        run: pnpm vp run -F react-responsive-modal build
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Publish react-responsive-modal npm package
        run: pnpm --filter react-responsive-modal publish --no-git-checks
        env:
          # Use OIDC for npm authentication instead of NPM_TOKEN
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
