name: size

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: react-responsive-modal
